The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `8`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
11/20/2024 20:07:07 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: bf16

DEVICE cuda:0
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 2
Local process index: 2
Device: cuda:2

Mixed precision type: bf16

DEVICE cuda:2
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 1
Local process index: 1
Device: cuda:1

Mixed precision type: bf16

DEVICE cuda:1
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 4
Local process index: 4
Device: cuda:4

Mixed precision type: bf16

11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 6
Local process index: 6
Device: cuda:6

Mixed precision type: bf16

DEVICE cuda:4
DEVICE cuda:6
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 5
Local process index: 5
Device: cuda:5

Mixed precision type: bf16

DEVICE cuda:5
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 7
Local process index: 7
Device: cuda:7

Mixed precision type: bf16

DEVICE cuda:7
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 20:07:08 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 8
Process index: 3
Local process index: 3
Device: cuda:3

Mixed precision type: bf16

DEVICE cuda:3
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  4.73it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.34it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.23it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.06it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.05it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.09it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.07it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  4.91it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  3.34it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  3.36it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.60it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.50it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.64it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.54it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.65it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.55it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.68it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.57it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.62it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.50it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  4.48it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  4.27it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  4.15it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  4.00it/s]
Init model
Init model
Init model
Init model
Init model
Init model
Init model
Init model
Loading checkpoint
Loading checkpoint
Loading checkpoint
Loading checkpoint
Loading checkpoint
Loading checkpoint
Loading checkpoint
Loading checkpoint
Init AE
Init AE
Init AE
Init AE
Init AE
Init AE
Init AE
Init AE
743.80728 parameters
743.80728 parameters
743.80728 parameters
743.80728 parameters
743.80728743.80728  parametersparameters

743.80728 parameters
743.80728 parameters
11/20/2024 20:08:29 - INFO - __main__ - ***** Running training *****
11/20/2024 20:08:29 - INFO - __main__ -   Num Epochs = 9
11/20/2024 20:08:29 - INFO - __main__ -   Instantaneous batch size per device = 3
11/20/2024 20:08:29 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 48
11/20/2024 20:08:29 - INFO - __main__ -   Gradient Accumulation steps = 2
11/20/2024 20:08:29 - INFO - __main__ -   Total optimization steps = 100000
Checkpoint 'latest' does not exist. Starting a new training run.
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
torch.Size([4]) torch.Size([4, 1536, 64]) torch.Size([4, 1536, 64])
Steps:   0%|          | 0/100000 [00:00<?, ?it/s][rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank1]:     main()
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank1]:     model_pred = dit(
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank1]:     img = block(img, vec=vec, pe=pe)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank1]:     return self.processor(self, x, vec, pe)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank1]:     attn_1 = attention(q, k, v, pe=pe)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank1]:     q, k = apply_rope(q, k, pe)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank1]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 1 has a total capacity of 79.32 GiB of which 69.50 MiB is free. Including non-PyTorch memory, this process has 79.25 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank2]: Traceback (most recent call last):
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank2]:     main()
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank2]:     model_pred = dit(
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank2]:     img = block(img, vec=vec, pe=pe)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank2]:     return self.processor(self, x, vec, pe)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank2]:     attn_1 = attention(q, k, v, pe=pe)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank2]:     q, k = apply_rope(q, k, pe)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank2]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank2]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 2 has a total capacity of 79.32 GiB of which 69.50 MiB is free. Including non-PyTorch memory, this process has 79.25 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank5]: Traceback (most recent call last):
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank5]:     main()
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank5]:     model_pred = dit(
[rank5]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank5]:     img = block(img, vec=vec, pe=pe)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank5]:     return self.processor(self, x, vec, pe)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank5]:     attn_1 = attention(q, k, v, pe=pe)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank5]:     q, k = apply_rope(q, k, pe)
[rank5]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank5]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank5]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 5 has a total capacity of 79.32 GiB of which 69.50 MiB is free. Including non-PyTorch memory, this process has 79.25 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank6]: Traceback (most recent call last):
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank6]:     main()
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank6]:     model_pred = dit(
[rank6]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank6]:     img = block(img, vec=vec, pe=pe)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank6]:     return self._call_impl(*args, **kwargs)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank6]:     return forward_call(*args, **kwargs)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank6]:     return self.processor(self, x, vec, pe)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank6]:     attn_1 = attention(q, k, v, pe=pe)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank6]:     q, k = apply_rope(q, k, pe)
[rank6]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank6]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank6]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 6 has a total capacity of 79.32 GiB of which 69.50 MiB is free. Including non-PyTorch memory, this process has 79.25 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank3]: Traceback (most recent call last):
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank3]:     main()
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank3]:     model_pred = dit(
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank3]:     return self._call_impl(*args, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank3]:     return forward_call(*args, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank3]:     img = block(img, vec=vec, pe=pe)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank3]:     return self._call_impl(*args, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank3]:     return forward_call(*args, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank3]:     return self.processor(self, x, vec, pe)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank3]:     attn_1 = attention(q, k, v, pe=pe)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank3]:     q, k = apply_rope(q, k, pe)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank3]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank3]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 3 has a total capacity of 79.32 GiB of which 69.50 MiB is free. Including non-PyTorch memory, this process has 79.25 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank7]: Traceback (most recent call last):
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank7]:     main()
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank7]:     model_pred = dit(
[rank7]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank7]:     img = block(img, vec=vec, pe=pe)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank7]:     return self._call_impl(*args, **kwargs)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank7]:     return forward_call(*args, **kwargs)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank7]:     return self.processor(self, x, vec, pe)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank7]:     attn_1 = attention(q, k, v, pe=pe)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank7]:     q, k = apply_rope(q, k, pe)
[rank7]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank7]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank7]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 7 has a total capacity of 79.32 GiB of which 21.50 MiB is free. Including non-PyTorch memory, this process has 79.30 GiB memory in use. Of the allocated memory 76.44 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank0]:     main()
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank0]:     model_pred = dit(
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank0]:     img = block(img, vec=vec, pe=pe)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank0]:     return self.processor(self, x, vec, pe)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank0]:     attn_1 = attention(q, k, v, pe=pe)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank0]:     q, k = apply_rope(q, k, pe)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank0]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 79.32 GiB of which 47.44 MiB is free. Including non-PyTorch memory, this process has 79.28 GiB memory in use. Of the allocated memory 76.44 GiB is allocated by PyTorch, and 387.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank4]: Traceback (most recent call last):
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank4]:     main()
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 240, in main
[rank4]:     model_pred = dit(
[rank4]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/model.py", line 224, in forward
[rank4]:     img = block(img, vec=vec, pe=pe)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 555, in forward
[rank4]:     return self.processor(self, x, vec, pe)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/modules/layers.py", line 496, in __call__
[rank4]:     attn_1 = attention(q, k, v, pe=pe)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 7, in attention
[rank4]:     q, k = apply_rope(q, k, pe)
[rank4]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/src/flux/math.py", line 28, in apply_rope
[rank4]:     xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
[rank4]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 96.00 MiB. GPU 4 has a total capacity of 79.32 GiB of which 69.50 MiB is free. Including non-PyTorch memory, this process has 79.25 GiB memory in use. Of the allocated memory 76.25 GiB is allocated by PyTorch, and 413.78 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Steps:   0%|          | 0/100000 [00:05<?, ?it/s]
[rank0]:[W1120 20:08:35.090162095 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1120 20:08:37.314069 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25707 closing signal SIGTERM
W1120 20:08:37.316910 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25708 closing signal SIGTERM
W1120 20:08:37.317430 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25710 closing signal SIGTERM
W1120 20:08:37.317842 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25711 closing signal SIGTERM
W1120 20:08:37.318214 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25712 closing signal SIGTERM
W1120 20:08:37.318605 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25713 closing signal SIGTERM
W1120 20:08:37.320360 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 25714 closing signal SIGTERM
E1120 20:08:38.326747 25476 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 25709) of binary: /mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/bin/python
Traceback (most recent call last):
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_flux_deepspeed_controlnet.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_20:08:37
  host      : SH-IDC1-10-140-0-137
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 25709)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: SH-IDC1-10-140-0-137: task 0: Exited with exit code 1
