The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `4`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
11/20/2024 19:42:13 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: bf16

DEVICE cuda:0
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/accelerator.py:443: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
11/20/2024 19:42:14 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 1
Local process index: 1
Device: cuda:1

Mixed precision type: bf16

11/20/2024 19:42:14 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 3
Local process index: 3
Device: cuda:3

Mixed precision type: bf16

11/20/2024 19:42:14 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 4
Process index: 2
Local process index: 2
Device: cuda:2

Mixed precision type: bf16

DEVICE cuda:1
DEVICEDEVICE  cuda:3cuda:2

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  1.72it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.97it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.92it/s]
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.01it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.27it/s]Loading checkpoint shards:  50%|█████     | 1/2 [00:00<00:00,  5.26it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.90it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.79it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.68it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.56it/s]
Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.87it/s]Loading checkpoint shards: 100%|██████████| 2/2 [00:00<00:00,  5.77it/s]
Init model
Init model
Init model
Init model
Loading checkpoint
Loading checkpoint
Loading checkpoint
Loading checkpoint
Init AE
Init AE
Init AE
Init AE
743.80728 parameters
743.80728 parameters
743.80728 parameters
743.80728 parameters
11/20/2024 19:42:46 - INFO - __main__ - ***** Running training *****
11/20/2024 19:42:46 - INFO - __main__ -   Num Epochs = 3
11/20/2024 19:42:46 - INFO - __main__ -   Instantaneous batch size per device = 1
11/20/2024 19:42:46 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 8
11/20/2024 19:42:46 - INFO - __main__ -   Gradient Accumulation steps = 2
11/20/2024 19:42:46 - INFO - __main__ -   Total optimization steps = 100000
Checkpoint 'latest' does not exist. Starting a new training run.
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1])torch.Size([1, 1536, 64])  torch.Size([1, 1536, 64])
torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
torch.Size([1]) torch.Size([1, 1536, 64]) torch.Size([1, 1536, 64])
Steps:   0%|          | 0/100000 [00:00<?, ?it/s]Steps:   0%|          | 0/100000 [00:03<?, ?it/s, lr=2e-5, step_loss=0.702]Steps:   0%|          | 1/100000 [00:04<121:14:45,  4.36s/it, lr=2e-5, step_loss=0.702]Steps:   0%|          | 1/100000 [00:04<121:14:45,  4.36s/it, lr=2e-5, step_loss=0.352][rank2]: Traceback (most recent call last):
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank2]:     main()
[rank2]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 229, in main
[rank2]:     block_res_samples = controlnet(
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank2]:     return self._call_impl(*args, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank2]:     return forward_call(*args, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1639, in forward
[rank2]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank2]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1528, in _pre_forward
[rank2]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank2]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank2]: making sure all `forward` function outputs participate in calculating loss. 
[rank2]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank2]: Parameters which did not receive grad for rank 2: double_blocks.1.txt_mlp.2.bias, double_blocks.1.txt_mlp.2.weight, double_blocks.1.txt_mlp.0.bias, double_blocks.1.txt_mlp.0.weight, double_blocks.1.txt_attn.proj.bias, double_blocks.1.txt_attn.proj.weight
[rank2]: Parameter indices which did not receive grad for rank 2: 58 59 60 61 62 63
[rank0]: Traceback (most recent call last):
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank0]:     main()
[rank0]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 229, in main
[rank0]:     block_res_samples = controlnet(
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1639, in forward
[rank0]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank0]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1528, in _pre_forward
[rank0]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank0]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank0]: making sure all `forward` function outputs participate in calculating loss. 
[rank0]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank0]: Parameters which did not receive grad for rank 0: double_blocks.1.txt_mlp.2.bias, double_blocks.1.txt_mlp.2.weight, double_blocks.1.txt_mlp.0.bias, double_blocks.1.txt_mlp.0.weight, double_blocks.1.txt_attn.proj.bias, double_blocks.1.txt_attn.proj.weight
[rank0]: Parameter indices which did not receive grad for rank 0: 58 59 60 61 62 63
[rank3]: Traceback (most recent call last):
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank3]:     main()
[rank3]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 229, in main
[rank3]:     block_res_samples = controlnet(
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank3]:     return self._call_impl(*args, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank3]:     return forward_call(*args, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1639, in forward
[rank3]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank3]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1528, in _pre_forward
[rank3]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank3]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank3]: making sure all `forward` function outputs participate in calculating loss. 
[rank3]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank3]: Parameters which did not receive grad for rank 3: double_blocks.1.txt_mlp.2.bias, double_blocks.1.txt_mlp.2.weight, double_blocks.1.txt_mlp.0.bias, double_blocks.1.txt_mlp.0.weight, double_blocks.1.txt_attn.proj.bias, double_blocks.1.txt_attn.proj.weight
[rank3]: Parameter indices which did not receive grad for rank 3: 58 59 60 61 62 63
[rank1]: Traceback (most recent call last):
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 318, in <module>
[rank1]:     main()
[rank1]:   File "/mnt/petrelfs/zhaoshitian/x-flux-forge/train_flux_deepspeed_controlnet.py", line 229, in main
[rank1]:     block_res_samples = controlnet(
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1639, in forward
[rank1]:     inputs, kwargs = self._pre_forward(*inputs, **kwargs)
[rank1]:   File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1528, in _pre_forward
[rank1]:     if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
[rank1]: RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
[rank1]: making sure all `forward` function outputs participate in calculating loss. 
[rank1]: If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
[rank1]: Parameters which did not receive grad for rank 1: double_blocks.1.txt_mlp.2.bias, double_blocks.1.txt_mlp.2.weight, double_blocks.1.txt_mlp.0.bias, double_blocks.1.txt_mlp.0.weight, double_blocks.1.txt_attn.proj.bias, double_blocks.1.txt_attn.proj.weight
[rank1]: Parameter indices which did not receive grad for rank 1: 58 59 60 61 62 63
Steps:   0%|          | 1/100000 [00:05<145:54:16,  5.25s/it, lr=2e-5, step_loss=0.352]
[rank0]:[W1120 19:42:52.410194430 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1120 19:42:54.296772 304172 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 304368 closing signal SIGTERM
W1120 19:42:54.299839 304172 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 304369 closing signal SIGTERM
W1120 19:42:54.300393 304172 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 304371 closing signal SIGTERM
E1120 19:42:54.778897 304172 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 304370) of binary: /mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/bin/python
Traceback (most recent call last):
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1159, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/accelerate/commands/launch.py", line 793, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/petrelfs/zhaoshitian/anaconda3/envs/xlab/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_flux_deepspeed_controlnet.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_19:42:54
  host      : SH-IDC1-10-140-0-231
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 304370)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: SH-IDC1-10-140-0-231: task 0: Exited with exit code 1
